language: python
python:
  - 2.7
install:
  - pip install sphinx sphinx_rtd_theme==0.2.0 sphinxcontrib.youtube sphinxcontrib-googleanalytics
script: make html
after_success:
  - ./push.sh
env:
  global:
    - secure: "kMCqO+VbNTVMh83ed72unx9+RFdntDXxZF6OeTiGNoUH1IdVGfWw89A7MmZ0fY/IKE+n3/gTrsiNgvZ7Muwlt0fvDUO6lgz5ZvmU6X/Rlua3y4hJpMeQHRl+imNMW78sRElqOnieT4skHBnH6DvKwXmbZ01soZT/HJPnYZgdIx5W748TGu6foFQ47PKhYOHQIBC0mN+Xevz6JbVHFjIotuDTNAo1BGShPIlAUs0wEZP+3y3pQ5wu9B18bwdKbLAOIyeu4hGz+ryK3EbmjfYxkPyXTK5t/mNyIwfB9FiQTrVDO7eeYvKvERAdbQPIL4fJffBLyBYeMwhz3hSAvHTrzeSDjZo4yuaIcrkHeb7477WmH1e6hRJazaL6cVNFRsBdOzMxomdMdih+pxl1k4TrbNSM9y+0YnawJf6p01wlQpehcXlLzIKX1q+XObYkP7+T5ku2Azm7wn0XCnKteF4eHvKbBKoJoret3ENtfrk7oh9sq10UWEldfahdC8HcdVpToEGdoJJme6c6sQlZAsas6zC//6flGLsKmdUWd4aY8aM680EwOCPZj2Exrr+CQ9ncv6Tjuk69PwF/ZJ9F8BdIuEt1oWpVNS8iwyDuqTlvbUetVU5Dbae+g65Uqjo8O5QCpzcoMgRoNWECEjvLu70IZKHKXYR6xxr1ZSPA2TqfvRA="
